import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ActiveLink } from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "next shop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<nav>
					<ul className="mt-2 flex justify-center space-x-4">
						<li>
							<ActiveLink href={"/"}>Home</ActiveLink>
						</li>
						<li>
							<ActiveLink href={"/products"}>All</ActiveLink>
						</li>
					</ul>
				</nav>

				<section className="mx-auto max-w-md p-12  sm:max-w-2xl sm:py-16 md:max-w-4xl lg:max-w-7xl">
					{children}
				</section>

				<footer className="text-center text-sm text-gray-500">&copy; 2023</footer>
			</body>
		</html>
	);
}
